// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"github.com/tokenlive/tokenlive-gateway/internal/handler"
	"github.com/tokenlive/tokenlive-gateway/internal/job"
	"github.com/tokenlive/tokenlive-gateway/internal/repository"
	"github.com/tokenlive/tokenlive-gateway/internal/router"
	"github.com/tokenlive/tokenlive-gateway/internal/server"
	"github.com/tokenlive/tokenlive-gateway/internal/service"
	"github.com/tokenlive/tokenlive-gateway/pkg/app"
	"github.com/tokenlive/tokenlive-gateway/pkg/jwt"
	"github.com/tokenlive/tokenlive-gateway/pkg/log"
	"github.com/tokenlive/tokenlive-gateway/pkg/server/http"
	"github.com/tokenlive/tokenlive-gateway/pkg/sid"
)

import (
	_ "github.com/tokenlive/tokenlive-gateway/pkg/llm/providers"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	redisConfig := repository.LoadRedisConfig(viperViper)
	client, cleanup, err := repository.NewRedis(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	modelService := service.NewModelService(client, logger, viperViper)
	gatewayProvider, err := ProvideGatewayProvider(viperViper, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	apiKeyService := service.NewApiKeyService(gatewayProvider, logger)
	configManager, err := NewGatewayConfigManager(viperViper, logger, client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	conn, cleanup2, err := repository.NewClickHouse(viperViper, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine, cleanup3, err := NewGatewayEngine(viperViper, logger, modelService, apiKeyService, configManager, client, conn, gatewayProvider)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	aliasService := service.NewAliasService(client, logger)
	llmHandler := handler.NewLLMHandler(engine, modelService, configManager, aliasService)
	routerDeps := router.RouterDeps{
		Logger:        logger,
		Config:        viperViper,
		JWT:           jwtJWT,
		UserHandler:   userHandler,
		LLMHandler:    llmHandler,
		ApiKeyService: apiKeyService,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.LoadRedisConfig, repository.NewRedis, repository.NewClickHouse, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewApiKeyService, service.NewModelService, service.NewAliasService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewLLMHandler, NewGatewayConfigManager,
	NewGatewayEngine,
	ProvideGatewayProvider,
)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("github.com/tokenlive/tokenlive-gateway"))
}
