version: '3'

services:
  cache-redis:
    image: redis:6-alpine
    hostname: cache-redis
    # volumes:
    #   - ./data/redis/cache/:/data
    #   - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6350:6379
    command: ["redis-server","/etc/redis/redis.conf"]
